she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    # path('', views.IndexView.as_view(), name='index')
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    # path('edit/<int:pk>', views.UpdateStoryView.as_view(), name='update_story'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    
]

she_codes_news/users/urls.py
# users/urls.py

from django.urls import path
from .views import CreateAccountView, UserAccountView

app_name ='users'

urlpatterns = [    
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>/', UserAccountView.as_view(), name='myAccount')
    
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    story_image = models.URLField(blank = True, null = True)

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    about = models.TextField(blank = True)
    user_img = models.URLField(blank = True)

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
# news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    class Meta:        
        model = NewsStory        
        fields = ['title', 'pub_date', 'content', 'story_image']
        widgets = {
            'pub_date': forms.DateInput(
                format='%m/%d/%Y',
                attrs={
                    'class':'form-control',
                    'placeholder':'Select a date',
                    'type':'date'
                }
            ),
        }

she_codes_news/users/forms.py
# users/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:        
        model = CustomUser        
        fields = ['username', 'email', 'about', 'user_img']
        
class CustomUserChangeForm(UserChangeForm):
    class Meta:        
        model = CustomUser        
        fields = ['username', 'email', 'about', 'user_img']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm


class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        return context
    
class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

# class UpdateStoryView(generic.UpdateView):
#     model=NewsStory
#     template_name = "news/update.html"
#     fields = ['title','category', 'image_url', 'pub_date', 'content']
#     success_url = reverse_lazy('news:index')

she_codes_news/users/views.py
from typing import Any
from django.db import models
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic

from news.models import NewsStory
from .models import CustomUser
from .forms import CustomUserCreationForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class UserAccountView(generic.DetailView):
    model = CustomUser
    template_name = 'users/myAccount.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['user_stories'] = NewsStory.objects.filter(author=user)
        return context
    
class AuthorDetailView(generic.DetailView):
    model = CustomUser
    template_name = 'news/Index.html'
    context_object_name = 'author'

    def get_object(self, *args, **kwargs):
        return get_object_or_404(CustomUser, username = self.kwargs['username'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_stories'] = NewsStory.objects.filter(author__id=self.object.id)
        return context

she_codes_news/news/templates/authorSearch.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}



    

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}


    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    

    <br>

    <h2>LATEST NEWS</h2>

    <br>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <br>
    <br>

    <h2>ALL STORIES</h2>

    <br>

    <div id="all-stories">

        <!-- <div id="author-container">
            <h2>Search Authors</h2>

        </div> -->

        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

{% endblock %}

she_codes_news/news/templates/news/story.html
<!-- news/templates/news/story.html -->
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}

    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}
{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4><a href="{% url 'users:myAccount' story.author.id %}">{{ story.author }}</a></h4>

    <p class="auth-pub">Posted: {{ story.pub_date|date:'d M y' }}</p>


    <div id="story-content">
        {% if story.story_image %}
        <img src="{{story.story_image}}">

        {% else %}
        <img src="https://picsum.photos/600">

        {% endif %}
        {{ story.content|linebreaks }}
    </div>
</div>


{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">   
    
    <a href="{% url 'news:story' story.id %}">

        {% if story.story_image %}
            <img src="{{story.story_image}}">

        {% else %}
            <img src="https://picsum.photos/600">
            
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>Written by {{ story.author }}</h4>
            <h4>Posted on {{ story.pub_date }}</h4>

        </div>
    </a>
</div>

she_codes_news/templates/base.html
<!-- templates/base.html -->

{% load static %}

<!doctype html>

<html lang="en"></html>

    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="YOUR NAME HERE">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>



        {% block content %}{% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>

    {% if request.user.is_authenticated %}
        <a href="{% url 'users:myAccount' request.user.id %}">Hi, {{ user.username }}!</a>
        <a href="{% url 'news:newStory' %}">Write News Story</a>
        <a href="{% url 'logout' %}">Logout</a>

    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:createAccount' %}">Create Account</a>

    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
    <h2>Create Account</h2>
    <form method="post">        
        {% csrf_token %}        
        {{ form.as_p }}
        <button type="submit">Create Account</button>
    
    </form>
    
    {% endblock %}

she_codes_news/users/templates/users/myAccount.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="my_profile">
    <h2>{{ user.username }}</h2>

    {% if request.user.is_authenticated %}
    <p>Email: {{ user.email }}</p>
    <p>About: {{ user.about }}</p>
    {% endif %}

    <img src="{{ user.user_img }}" alt="Profile Pic">
    <div id="user_stories">
        <h3>Stories Posted:</h3>
        
        {% for story in user.newsstory_set.all %}
            <div class="acc_story_grid">
                <h4><a href="{% url 'news:story' story.id %}">{{ story.title }}</a></h4>
            </div>
        {% endfor %}
    </div>

</div>

{% endblock %}